name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.18.0"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run prettier
      - name: build
        run: npm run build
      - name: test
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start:e2e
          wait-on: http://localhost:3003
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fspart11-bloglist
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://fspart11-bloglist.herokuapp.com/health
          rollbackonhealthcheckfailed: false
  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
